### ISSUE TITLE
Warnings at the end of package install/update

### ISSUE THREAD

**Issue by jolla** [WLAN-Pi/wlanpi-kernel#3]
W: Possible missing firmware /lib/firmware/rtl_nic/rtl8156b-2.fw for built-in driver r8152
W: Possible missing firmware /lib/firmware/rtl_nic/rtl8156a-2.fw for built-in driver r8152
W: Possible missing firmware /lib/firmware/rtl_nic/rtl8153c-1.fw for built-in driver r8152
W: mkconf: MD subsystem is not loaded, thus I cannot scan for arrays.
W: mdadm: failed to auto-generate temporary mdadm.conf file.

**Comment by danielmundi** [comment]
`mdadm` is installed as a dependency from `cockpit-storaged`.
It is not necessary and doesn't do anything on the Pi, because it's used for handling HDs in RAID. This warning doesn't affect anything.

The other warning about the possible missing FW are probably related to the new kernel installed while some firmware were not updated yet. I don't believe it's a problem, since the driver should still load the old firmware present on the system. But would need to double check that.

**Comment by jolla** [comment]
I'm guessing the firmware warnings are related to this, which isn't likely needed
https://github.com/WLAN-Pi/wlanpi-kernel/blob/cc80a6951eb673b28a79207a40409e464f5164aa/wlanpi_v8_defconfig#L34

**Comment by joshschmelzle** [comment]
These warnings also happened on install for the latest version I built today for arm64.
